# generated by datamodel-codegen:
#   filename:  project.schema.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra, Field

from . import load_profile as load_profile_1


class Zone(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    enabled_modules: List[str] = Field(..., min_items=1)
    factor: Optional[float] = Field(
        1,
        description="Мультипликатор зоны (>=1). 1 — поведение без изменений.",
        ge=1.0,
    )
    load_profile: load_profile_1.Schema


class PrismProjectSizingFile(BaseModel):
    class Config:
        extra = Extra.forbid

    customer: str
    zones: List[Zone]
