# generated by datamodel-codegen:
#   filename:  project.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra, Field


class Schema(BaseModel):
    class Config:
        extra = Extra.forbid

    online_users: int = Field(..., ge=0)
    total_users: int = Field(..., ge=0)
    rps: int = Field(..., ge=0)
    rps_p95: int = Field(..., ge=0)
    jobs_rate: Optional[int] = Field(None, ge=0)
    structured_data_gb: float = Field(..., ge=0.0)
    unstructured_data_gb: float = Field(..., ge=0.0)
