# generated by datamodel-codegen:
#   filename:  blueprint.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra

from . import ResourceFormula, ResourceQuantity


class Static(BaseModel):
    class Config:
        extra = Extra.forbid

    requests: ResourceQuantity
    limits: ResourceQuantity


class Dynamic(BaseModel):
    class Config:
        extra = Extra.forbid

    requests: ResourceFormula
    limits: ResourceFormula


class Schema(BaseModel):
    class Config:
        extra = Extra.forbid

    static: Optional[Static] = None
    dynamic: Optional[Dynamic] = None
